###
GET http://127.0.0.1:8000/?emoji

###
GET http://127.0.0.1:8000/?name=Rocketeer

###
GET http://127.0.0.1:8000/?lang=ру

###
GET http://127.0.0.1:8000/?lang=ру&emoji

###
GET http://127.0.0.1:8000/?emoji&lang=en

###
GET http://127.0.0.1:8000/?name=Rocketeer&lang=en

###
GET http://127.0.0.1:8000/?emoji&name=Rocketeer

###
GET http://localhost:8000/hello/world

###
GET http://localhost:8000/hello/foo/ignore/bar

###
GET http://localhost:8000/hello/anything/404

###
GET http://localhost:8000/hello/delay/4

###
GET http://localhost:8000/hello/serve_text_file

###
GET http://localhost:8000/hello/page/parent/data.txt

###
GET http://localhost:8000/hello/greeting/Hai/30/false

###
GET http://localhost:8000/hello/user/1

###
GET http://localhost:8000/hello/user/string_value

# ** Bookmark start ********************

### go to twitter
http://localhost:8000/search?cmd=tw

### visit a profile
http://localhost:8000/search?cmd=tw%20@fbOpenSource

### search for tweets
http://localhost:8000/search?cmd=tw%20rust%20lang

### navigate to Github
http://localhost:8000/search?cmd=gh

### navigate to Github react repository
http://localhost:8000/search?cmd=gh%20facebook/react

# ** Bookmark end **********************
