###
GET http://localhost:8000/hello/world

###
GET http://localhost:8000/hello/foo/ignore/bar

###
GET http://localhost:8000/hello/anything/404

###
GET http://localhost:8000/hello/delay/4

###
GET http://localhost:8000/hello/serve_text_file

###
GET http://localhost:8000/hello/page/parent/data.txt

###
GET http://localhost:8000/hello/greeting/Hai/30/false